---
title: "Rapport Final"
author: "Joël Ducasse, Ahlin Roland Césaire Tchintchin, Marc-Antoine Dion et Alexandre Quirion"
date: "Le vendredi 1 mai 2026"
output: pdf_document
---

## Mandat
Le mandat principal de ce projet était de réaliser une application Shiny pour prédire les scores futurs d'un golfeur. De plus, nous devions implanter 3 modèles de crédibilités différents dans cette application. Pour notre part, nous avons décidé de prendre le modèle bayésien, le modèle de Bühlmann et le modèle de Bühlmann-Straub. L'application que nous avons réalisé permet à l'utilisateur de choisir le modèle qu'il souhaite utiliser pour prédire les scores futurs.

De plus, pour cette étape finale, nous avions à réaliser une courte vidéo explicative sur les modèles de notre application. C'est à dire que nous avons décrit les 3 modèles cités plus tôt lors de cette vidéo. Aussi, nous devions effectuer des tests statistiques pour suggérer un modèle aux utilisateurs et nous devions remplir le fichier de données partielles fourni avec l'énoncé du travail avec le modèle suggéré. Enfin, la dernière étape de ce mandat était la réalisation de ce rapport final.


## Réalisations

Tout d'abord, nous avons effectués la correction de petits détails dans l'application. Nous avons essayé de corriger le plus d'erreurs possibles que nos modèles pouvais avoir. Pour tenter d'avoir les modèles les plus précis, nous avons effectués quelques tests. En effet, nous essayions de savoir si les résultats obtenus avaient du sens. Par exemple, nous regardions si les facteurs de crédibilité ($\hat{z_i}$) était cohérents. Plus précisément, nous regardions si plus il y avait de données inscrites, plus le facteur de crédibilité était grand pour l'expérience individuelle. De plus, nous nous assurions que le max soit de 0,50 puisque sinon ce n'est pas cohérent.

Par la suite, nous avons effectué la comparaison des trois modèles que nous avions implantés dans l’application. Il s'agit du modèle bayésien (Poisson/Gamma), du modèle de Bühlmann et du modèle de Bühlmann-Straub.

Pour évaluer ces trois modèles, nous avons utilisé les données complètes disponibles et simulées des rondes partielles en ne conservant qu’un certain nombre de trous joués. Plus précisément, nous avons enlevé aléatoirement des coups de golf dans les données complètes pour ensuite effectuer les tests. Par exemple, il y a des rondes où le golfeur aura joué les coups 1, 2 et 3. Tandis que parfois, il sera indiqué que le golfeur aura joué les coups 4, 5, 6, 7 et 8. Ceci nous permet de tester si notre modèle est capable de prédire les scores futurs et nous permet de comparer les résultats que nous obtenons aves les véritables scores qui sont dans le fichier de données complètes. Par la suite, nous avons utilisé chaque modèle pour complèter ce nouveau jeu de données. De plus, nous avons effectué des tests statistiques en comparant les résultats avec les données complètes.

Pour comparer les modèles de crédibilité, nous avons utilisé les tests statistiques suivants :

\begin{itemize}
    \item \textbf{MAE (Mean Absolute Error)} : Mesure l'erreur moyenne absolue entre la prédiction et la valeur réelle.
    \item \textbf{RMSE (Root Mean Squared Error)} : Mesure qui pénalise davantage les grandes erreurs.
    \item \textbf{Biais} : Moyenne des erreurs et il indique si le modèle surestime ou sous-estime les scores.
\end{itemize}


Voici les résultats que nous avons obtenus pour les différents modèles :

\begin{itemize}
    \item \textbf{Bühlmann} : MAE = 3.05, RMSE = 4.54, Bias = 0.17
    \item \textbf{Bühlmann-Straub} : MAE = 3.05, RMSE = 4.54, Bias = 0.16
    \item \textbf{Bayésien Poisson/Gamma} : MAE = 3.43, RMSE = 4.90, Bias = 0.47
\end{itemize}

Lorsque nous observons les résultats du MAE, nous remarquons que les modèles de Bühlmman et de Bühlmann-Straub sont plus performants. En effet, le modèle de Bühlmann présente un MAE d’environ 3.05, ce qui nous indique que les prédictions de ce modèle s’écartent d’environ 3 coups du score réel. Le modèle de Bühlmann-Straub obtient le même résultat selon les résultats dans notre tableau. Il a donc, aussi, un résultat de 3.05. Nous pouvons donc penser que ces deux modèles ont une performance presque équivalente selon ce test. Cependant, pour le modèle bayésien, nous remarquons une MAE plus élevée. Elle est d'environ 3.43 pour ce modèle. Nous concluons donc que ce modèle est moins précis que les deux autres modèles selon cette métrique.

Par la suite, nous regardons le test de la MSE. Nous obtenons les mêmes conclusions que le test précédent (MAE). En effet, les modèles de Bühlmann et de Bühlmann-Straub présentent des résultats plus faibles que le modèle bayésien. Ces deux modèles ont ainsi une meilleure gestion des grandes erreurs de prédiction. Le modèle bayésien est donc plus sensible aux écarts importants entre les prédictions et les valeurs réelles. En effet, le résultat d'environ 4.54 pour les modèles de Bühlmann et de Bühlmann-Straub est moins élevé que le résultat d'environ 4.90 pour le modèle bayésien.

Enfin, le dernier test statistique que nous analysons dans ce rapport est le biais. Ce test nous permet de vérifier si un modèle a tendance à surestimer ou sous-estimer les scores comme nous l'avions précisé plus tôt. En observant nos résultats, les trois modèles présentent un biais relativement faible, ce qui indique qu’ils ne présentent pas de tendance systématique importante. Cependant, nous remarquons que le résultat du modèle bayésien est encore une fois plus élevé que ceux des deux autres modèles. En effet, en regardant le tableau, on remarque que son résultat est de 0.47, tandis que pour les modèles de Bühlmann et de Bühlmann-Straub, 0,17 et 0,16 sont leur résultat respectif. Nous concluons donc encore que les modèles de Bühlmann et de Bühlmann-Straub sont plus performants que le modèle bayésien et qu'ils sont très semblables.

À l'aide des résultats précédents, nous concluons que le meilleur modèle et celui que nous proposons d'utiliser aux utilisateurs est le modèle de Bühlmann-Straub. En effet, ce modèle obtient de meilleurs résultats dans les tests statistiques que le modèle Bayésien. Il est semblable au modèle de Bühlmann, mais on remarque que le modèle de Bühlmann-Straub a un biais légèrement plus faible. C'est donc pour cela que nous proposons le modèles de Bühlman-Straud aux utilisateurs de l'application.

De plus, sur l'application, vous pouvez regarder les résultats des tests pour chaque modèle. Ils sont affichés à la section << Comparaison des modèles >>.

Ensuite, nous devions réaliser une vidéo explicative des modèles de crédibilité en lien avec notre mandat. Nous avons donc séparé les parties de la vidéo en équipe et réalisé chacune des parties affectées chacun de notre coté. Après avoir réalisé chacun notre partie, nous avons effectué un montage vidéo pour tout assembler et essayer de rendre le plus cohérent.

Enfin, la dernière réalisation de ce mandat était le rapport final. Nous avons donc réalisé ce rapport en émettant nos conclusions et nos commentaires sur l'ensemble de ce projet.

## Apprentissage

Lors de ce mandat, nous avons appris plusieurs éléments. Tout d'abord, puisque le mandat principal était la réalisation d'une application Shiny, nous avons beaucoup appris à coder en R et à réaliser une application Shiny. En effet, nous avons travaillé fort pour implanter les modèles de crédibilité dans cette application. Il s'agissait d'un grand défi et il s'agit fort probablement du plus grand apprentissage de ce mandat. 

De plus, nous avons appris avons découvert comment réaliser un montage vidéo. En effet, nous avions quelques bases sur cela, mais personne d'entre nous en avais véritablement réalisé un précédemment. Nous avons donc appris quelques trucs pour rendre le tout bien dans cet élément.

Enfin, lors des séances en classes, nous avons étudié différents modèles de crédibilité. Ce mandat nous a permis d'appronfondir ces modèles. De plus, nous avons appris deux différentes méthodes pour calculer les réserves qui nous seront fort probablement utiles lors de notre futur métier.


## Point amélioré

Nous avons utilisé chacun des modèles de crédibilité pour les adapter à notre situation. Donc, nous nous sommes améliorés dans les différents modèles de crédibilité auxquels nous avons recourus, car nous avons effectué quelques recherches et nous les avons utilisées dans la situation de ce mandat.

De plus, nous nous sommes tous améliorés en programmation R. Plus précisément, une grande partie du mandat était la réalisation d'une application Shiny. Pour cette étape, nous devions effectuer de la programmation pour implanter nos modèles de crédibilité et pour réaliser une bonne application. Donc, nous avons perfectionné nos connaissances dans le style de codage R et dans la réalisation d'une application Shiny.

## Difficulté du mandat

Lors de ce mandat, selon nous, l'élément le plus difficile était la réalisation de l'application. En effet, nous avons réalisé un très gros code informatique pour être capable d'obtenir l'application souhaité. De plus, nous devions être d'accord sur l'implantation des modèles et sur l'application en général. En effet, nous n'avions pas toujours les mêmes idées de réalisation. Donc, nous avions régulièrement discuté et argumenté lors de la réalisation de cette application. 

Aussi, un autre point difficile était probablement la vidéo. Il ne s'agit pas d'une tâche difficile, mais nous trouvions les instructions vagues. Nous avons donc réalisé une vidéo explicative comme nous le pensons. 

## Détail supplémentaire sur l'application

Dans cette section, nous allons simplement vous expliquer brièvement notre application. Tout d'abord, vous pouvez choisir le modèle que vous voulez. Cependant, le premier modèle qui vous est suggéré est le modèle de Bülhmann puisque c'est celui-ci qui nous donnait les meilleurs résultats dans les tests statistiques (ainsi que Bülhmann-Straub). Par la suite, selon le parcours de golf, vous indiquez la normale du total de nombres joués et le trou avec lequel le joueur commence. Initialement, le code indique que le joueur débute au trou numéro 1 et qu'il est sur un parcours de normale totale de 72 coups. Ensuite, vous indiquez les résultats obtenus par le joueur dans les bonnes cases. Enfin, vous appuyez sur << Calculer les prévisions >>. Vous obtiendrez les résultats des scores futurs du golfeur.

De plus, il y a un guide d'utilisation et les résultats de nos tests statistiques dans l'applications. Il est aussi possible pour vous de voir les jeux de données que nous avons utilisés pour pratiquer notre jeu de données. Enfin, il est important que vous ouvrez l'application Shiny avec les fichiers des données partielles, des données complètes et des données de normales. Sinon, il est possible que l'application ne fonctionnne pas parfaitement.

## Conclusion

En conclusion, lors de ce mandat, nous avons réalisé plusieurs petits rapports pour expliquer notre raisonnement et pour émettre un suivi. En revanche, les parties principales du projet étaient la réalisation d'une application Shiny ainsi que d'une vidéo explicative de notre projet, ouis finalement le choix de notre meilleur modèle de crédibilité à l'aide des tests statistiques.

Comme nous l'avons énoncé précédemment, nous avons obtenu, à l'aide des tests statistiques, que le modèle de Bühlmann-Straub est le meilleur. Nous suggérons donc aux utilisateurs de l'application d'utiliser ce modèle pour prédire les scores futurs d'un golfeur à l'aide de notre application. Lorsque vous ouvrez cette application, le modèle de Bühlmann-Straub sera déjà sélectionné de base.

Enfin, nous avons aimé réaliser ce mandat ainsi que toutes les étapes pour y parvenir. Ce mandat nous a permis d'approfondir la matière enseignée lors des séances de classe. De plus, ce rapport nous a permis d'explorer les modèles de crédibilité sous un angle différent, qui peut s'avérer utile pour notre futur travail en assurance. 
